### ISSUE TITLE
tdg.lookup.cypher causes NotInTransactionException: This transaction has already been closed

### ISSUE THREAD

**Issue by i2aymond** [neo4j-contrib/neo4j-faker#6]
I was trying to run example2.props from the example provided but I see the following error:

```
org.neo4j.graphdb.NotInTransactionException: This transaction has already been closed.
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.assertTransactionOpen(KernelTransactionImplementation.java:678)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.assertOpen(KernelTransactionImplementation.java:690)
	at org.neo4j.kernel.impl.newapi.Read.nodeLabelScan(Read.java:321)
	at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundReadQueryContext.getNodesByLabel(TransactionBoundQueryContext.scala:770)
	at org.neo4j.cypher.internal.planning.ExceptionTranslatingReadQueryContext.getNodesByLabel(ExceptionTranslatingQueryContext.scala:173)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.NodeByLabelScanPipe.internalCreateResults(NodeByLabelScanPipe.scala:37)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.Pipe.createResults(Pipe.scala:43)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.Pipe.createResults$(Pipe.scala:40)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.NodeByLabelScanPipe.createResults(NodeByLabelScanPipe.scala:30)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:78)
	at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:69)
	at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:90)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:144)
	at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchResults(ResultSubscriber.java:362)
	at org.neo4j.cypher.internal.javacompat.ResultSubscriber.nextFromSubscriber(ResultSubscriber.java:330)
	at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchNextOrNull(ResultSubscriber.java:301)
	at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchNextOrNull(ResultSubscriber.java:58)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
	at org.neo4j.internal.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
	at org.neo4j.faker.core.TestDataLoader.loadData(TestDataLoader.java:134)
	at org.neo4j.faker.ump.TestDataGen$1.write(TestDataGen.java:99)
	...
```

After looking into it further, I see the issue lies in these lines in example2.props:
```
tdg.lookup.nodes.list=matchCities
tdg.lookup.cypher.matchCities=match (cit:City) return cit
tdg.rel.list=companyCity
tdg.rel.def.companyCity=comp,LOCATED_IN,matchCities.cit,n-1
```

I believe the issue is when it tries to create `companyCity` relationship, it evaluates `matchCities`, but transaction is closed after `matchCities` evaluation, so the next action to create `companyCity` fails in neo4j 4.x

**Comment by kvegter** [comment]
This is fixed in version 0.9.5
